# Generated by Django 3.2.2 on 2021-09-17 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('cnp', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.pacient')),
            ],
        ),
    ]
